main: add missing header for non-glibc after 899843978ebd
src/main.cpp:7:17: error: use of undeclared identifier 'basename'
  string name = basename(argv[0]);
                ^